//=========================================================
// src/Interrupts.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================

// USER INCLUDES
#include <SI_EFM8BB1_Register_Enums.h>
#include <rtx51tny.h>
#include "DeviceConfig.h"

//-----------------------------------------------------------------------------
// ADC0EOC_ISR
//-----------------------------------------------------------------------------
//
// ADC0EOC ISR Content goes here. Remember to clear flag bits:
// ADC0CN0::ADINT (Conversion Complete Interrupt Flag)
//
//-----------------------------------------------------------------------------

SI_INTERRUPT(ADC0EOC_ISR, ADC0EOC_IRQn) {
	ADC0CN0_ADINT = false;
	isr_send_signal(TASK_ID_SENSORS);
}

//-----------------------------------------------------------------------------
// TIMER2_ISR
//-----------------------------------------------------------------------------
//
// TIMER2 ISR Content goes here. Remember to clear flag bits:
// TMR2CN0::TF2H (Timer # High Byte Overflow Flag)
// TMR2CN0::TF2L (Timer # Low Byte Overflow Flag)
//
//-----------------------------------------------------------------------------

SI_INTERRUPT(TIMER2_ISR, TIMER2_IRQn) {
	TMR2CN0_TF2H = false;
	O_BUZZER ^= O_BUZZER;
}

//-----------------------------------------------------------------------------
// TIMER3_ISR
//-----------------------------------------------------------------------------
//
// TIMER3 ISR Content goes here. Remember to clear flag bits:
// TMR3CN0::TF3H (Timer # High Byte Overflow Flag)
// TMR3CN0::TF3L (Timer # Low Byte Overflow Flag)
//
//-----------------------------------------------------------------------------

uint8_t data interval = 0;

SI_INTERRUPT(TIMER3_ISR, TIMER3_IRQn) {
	TMR3CN0 &= ~TMR3CN0_TF3H__SET;
	interval++;
}

//-----------------------------------------------------------------------------
// SMBUS0_ISR
//-----------------------------------------------------------------------------
//
// SMBUS0 ISR Content goes here. Remember to clear flag bits:
// SMB0CN0::SI (SMBus Interrupt Flag)
//
//-----------------------------------------------------------------------------

uint8_t data smbus_state;

SI_INTERRUPT (SMBUS0_ISR, SMBUS0_IRQn)
{
	SMB0CN0_SI = false;
}
